%% MOR_IncBase_Read
%  Read data generated by script: MOR_IncBase
%
% Modifications:
% 06-01-2017, WeiX, First edition
clear

%% Load data
load('Run_Train80Test300SS10U5to50.mat')

%%
% nPOD=n_Ubases;
% figure
% boxplot(RE_G(:,nPOD))
% figure
% boxplot(RE_K(:,nPOD))
% 
% figure
% boxplot(SSE_G(:,nPOD))
% figure
% boxplot(SSE_K(:,nPOD))
% 
% figure
% boxplot(RSSE_G(:,nPOD))
% figure
% boxplot(RSSE_K(:,nPOD))

%%
% nPOD=5:5:50;
nPOD=n_Ubases;

figure
boxplot(RE_G(:,nPOD))
% title(sprintf('SSE Global basis. Num_{Trian}=%0i, Num_{Test}=%0i, Num_{Snapshot}=%0i, Num_{Basis}=%0i',Num_Train,Num_Test,Num_Snapshot,n_Ubases))
hold off

xlabel('POD basis dimension');
ylabel('Square error');
title('(b)');

set(gca,'yscale','log');

ax = gca; 
ax.YScale='log';
%Range for log scale
ax = gca; 
uB=-1;
dB=-6;

ax.YLim=[10^dB,10^uB];
ytick=logspace(dB,uB,uB-dB+1);
ax.YTick=ytick;
ax.XTick=nPOD;
ax.XTick=1:length(nPOD);
ax.XTickLabel=nPOD;

%% 
figure
boxplot(RE_K(:,nPOD))
% title(sprintf('SSE %s, Num_{Trian}=%0i, Num_{Test}=%0i, Num_{Snapshot}=%0i, Num_{Basis}=%0i, Num_{DimNew}=%i', DrMethod,Num_Train,Num_Test,Num_Snapshot,n_Ubases,dim_new))
hold off

xlabel('POD basis dimension');
ylabel('Relative error');
title('(a)');
set(gca,'yscale','log');

ax = gca; 
ax.YScale='log';
%Range for log scale
ax = gca; 
uB=-1;
dB=-6;

ax.YLim=[10^dB,10^uB];
ytick=logspace(dB,uB,uB-dB+1);
ax.YTick=ytick;

ax.XTick=1:2:15;
ax.XTickLabel=1:2:15;

ax.XTick=nPOD;
ax.XTick=1:length(nPOD);
ax.XTickLabel=nPOD;

%%
nPOD=15;
RE=RE_K(:,nPOD);
[DecsRE,DecIndex]=sort(RE,'descend');
DecsRExStar=X_star(DecIndex,:);



[DecsRE_K,DecIndex_K]=sort(RE_K(:,nPOD),'descend');
DecsRExStar_K=X_star(DecIndex_K,:);

[DecsRE_G,DecIndex_G]=sort(RE_G(:,nPOD),'descend');
DecsRExStar_G=X_star(DecIndex_G,:);



%%
nPOD=15;
RE=RE_K(:,nPOD);

meanRe=mean(RE);
minRE=min(RE);
maxRE=max(RE);
QuantileRE=quantile(RE,[.25 .5 .75]);


CompareValue=1.5*quantile(RE,[.75]);
CompareValue=meanRe;
CompareValue=maxRE;


sortRE=(RE-CompareValue).^2;
[sortRE,sortRE_Index]=sort(sortRE);
SortX_star=X_star(sortRE_Index,:);

% relativeError=sortRE(sortRE_Index(1),:)
index=sortRE_Index(1)
xStar=X_star(sortRE_Index(1),:)

% T =reshape(Y_Full(:,i),Paras.Num_node_y,Paras.Num_node_x);


